### ISSUE TITLE
Ghouls N' Ghosts blades drawn behind wooden posts

### ISSUE THREAD

**Issue by cacophony1** [MiSTer-devel/SMS_MiSTer#10]
In Ghouls N Ghosts on the first stage, the blades that drop down are drawn behind the two wood posts instead of in front of them.

Stating at 52 seconds you can see how it's supposed to look: https://www.youtube.com/watch?time_continue=52&v=mdozrRd4AyM

**Comment by damopinn** [comment]
This looks ok, after the recent updates.

**Comment by sorgelig** [comment]
good.
