### ISSUE TITLE
mra - Riddle of Pyhatoras can't be rotated

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/SMS_MiSTer#106]
The game runs sideways / rotated with no way to rotate it "correctly".

**Comment by KremlingKuthroat19** [comment]
Yeah. I was going to submit a ticket for this, but you beat me to it. The same issue exists with the arcade version of Megumi Rescue too

**Comment by RGarciaLago** [comment]
This is fixed and the bug should be closed.
