### ISSUE TITLE
PAL speed not matching original hardware

### ISSUE THREAD

**Issue by MarkEire** [MiSTer-devel/SMS_MiSTer#109]
Noticed small speed difference in music at first, but experimented to observe the whole core appears to run faster than my SMS.

**SMS**: Master System II Power Base PAL-I. Model No: 3006-05 (Purchased in UK)
**MiSTer**: Not sure if any INI settings might effect this? I've kept a backup copy if any setting values are needed, eg. "vsync_adjust=0". SMS core settings: "TV System: PAL"

Attempt to quantify the difference using "**_Sonic The Hedgehog 2 (Europe, Brazil) ~~(Rev 1)~~_**".
**_(EDIT: Confirmed behaviour is on Ver1.00 ROM in viewing ROM in Hex. Same ROM used on console, dumped my cartridge using a Retrode)_**
Starting new game from main menu button press, quickly starting stop watch, recording the time on MiSTer and SMS console when Sonic ran out of all lives. Error propagation presented assuming I was way worse at timing than I should have reasonably been.

- SMS console: **2183.9±1 seconds**

- MiSTer: **2200.7±1 seconds**

- MiSTer speed factor compared to console: **1.0077±0.007**

I appreciate you'd need solid data to compare, I'm happy to provide anything else than I can.
I'd also acknowledge the difference could of course be my old hardware. I've reached out looking for other PAL SMS console players to similarly test, but no takers yet.
I did try an emulator, and found it ran the game slower than MiSTer, but still faster than my SMS console.

Thanks very much. Giving info in hopes of helping to achieving accuracy, but incredibly grateful for the core.

**Comment by sorgelig** [comment]
i will add master clock change for PAL

**Comment by sorgelig** [comment]
try this build:
[SMS.zip](https://github.com/MiSTer-devel/SMS_MiSTer/files/7237470/SMS.zip)

**Comment by MarkEire** [comment]
Thanks very much for the very fast response.
Downloaded and will test this build as soon as I've eaten. At a glance running Sonic 2 right now it looks identical. I had intended to record the audio from my Console and MiSTer and align the audio in Audacity or something to confirm the speed difference.

How was the current change in speed determined? If those files would still help I'll still record audio files now as I test the build in about an hour.

**Comment by sorgelig** [comment]
Master clock now is set to correct one separately for NTSC and PAL. 
If there are some incorrect implementations in some parts of core affecting the speed, then it won't be fixed soon i think.

**Comment by MarkEire** [comment]
I ran Golden Axe Warrior for around 30 minutes and returned to find the audio still in sync, so it looks like that did fix it. I was curious if you could see the actual difference in the code or something, presumably not quiet my 1.0077 value.

I'm noting all my cartridges here alongside ROM dumps to compare everything I have.
I'll keep testing cartridges, I have about 20. I'm not sure any are particularly odd test cases.

- Golden Axe Warrior notable requires MiSTer BIOS disabled to run in PAL, not seen that yet in any other Carts.
- Some of my games are ones with FM audio.

I'll just test them all for the next while, let some run for a long while to check music stays in sync.

**Comment by MarkEire** [comment]
Closing as now incorporated into latest build.
Thank you so much
