### ISSUE TITLE
Letterbox Game Gear before scaling

### ISSUE THREAD

**Issue by jlancaster86** [MiSTer-devel/SMS_MiSTer#114]
Given there's (currently) no way to apply "vscale_border" to the Game Gear and _not_ the Master System, would it be possible to add a toggle to letterbox the Game Gear's 144p video to 240p before it's scaled?

**Comment by birdybro** [comment]
Try out the new extended resolution mode and see if that serves your purpose somewhat.

**Comment by jlancaster86** [comment]
If there were an option for the additional pixels to be just black, that would be perfect.

**Comment by birdybro** [comment]
That kind of thing would work differently. I think for now you should try using Alternate MiSTer.ini's.

https://mister-devel.github.io/MkDocs_MiSTer/advanced/ini/#alternate-mister-ini-files

**Comment by RGarciaLago** [comment]
This issue was resolved by including an MGL file to use when playing Game Gear: https://github.com/MiSTer-devel/SMS_MiSTer/pull/158

@sorgelig / @birdybro this issue should Closed as completed.
