### ISSUE TITLE
Populous: broken audio sample at startup

### ISSUE THREAD

**Issue by Thelypody** [MiSTer-devel/SMS_MiSTer#136]
Populous (Europe, Brazil) (En).sms
CRC32: C7A1FDEF

This SMS game is supposed to play a voice sample at startup saying "Welcome to Populous". On the current core version (20220620) this audio sample has issues with playback, resulting in very low volume, making it nearly inaudible compared to game's PSG music.

SMS Power has a page dedicated to Populous sound samples:
https://www.smspower.org/Development/Populous-SMS

**Comment by sorgelig** [comment]
Probably @jotego as an author of PSG module may say if module is compatible with such trick.

**Comment by jotego** [comment]
@Thelypody could you share a link to a youtube video where the audio sample can be heard?

**Comment by Thelypody** [comment]
Not quite a Youtube video but an article from Nicole Express blog on playing sound samples on SMS has two video clips of Populous intro in the middle. I believe the author uses real hardware for demonstration.
http://nicole.express/2022/let-me-show-you-the-sound-of-my-master.html

**Comment by jotego** [comment]
Freezing the channel output bit for tones below 6 may fix the issue.
I cannot test it because of issue #137

**Comment by birdybro** [comment]
https://github.com/MiSTer-devel/SMS_MiSTer/issues/74 - possibly related.

**Comment by jotego** [comment]
I've fixed it, PR done, waiting for the merge acceptance. 

The explanation is that the internal DAC didn't react for very high frequencies. Originally I had assumed only the top two fastest ones, but it looks like tone code 5 didn't produce a switching output either. Extending the DAC deaf tones upto code 5 brings this voice samples backs to life.

**Comment by birdybro** [comment]
Thank you! :)

**Comment by Thelypody** [comment]
Just checked Populous with an unstable core build and got welcomed with a working sound sample. Thanks for quickly solving this edge case!
