### ISSUE TITLE
Cannot compile the core

### ISSUE THREAD

**Issue by jotego** [MiSTer-devel/SMS_MiSTer#137]
It looks like there is something wrong in the core files at the moment (commit 6be6652) as attempting to compile it generates errores related to the PLL:

Error (12006): Node instance "pll_hdmi" instantiates undefined entity "pll_hdmi". Ensure that required library paths are specified correctly, define the specified entity, or change the instantiation. If this entity represents Intel FPGA or third-party IP, generate the synthesis files for the IP.
Error (12006): Node instance "pll_cfg" instantiates undefined entity "pll_cfg". Ensure that required library paths are specified correctly, define the specified entity, or change the instantiation. If this entity represents Intel FPGA or third-party IP, generate the synthesis files for the IP.
Error (12006): Node instance "pll_audio" instantiates undefined entity "pll_audio". Ensure that required library paths are specified correctly, define the specified entity, or change the instantiation. If this entity represents Intel FPGA or third-party IP, generate the synthesis files for the IP.
Error (12006): Node instance "pll" instantiates undefined entity "pll". Ensure that required library paths are specified correctly, define the specified entity, or change the instantiation. If this entity represents Intel FPGA or third-party IP, generate the synthesis files for the IP.
Error (12006): Node instance "pll_cfg" instantiates undefined entity "pll_cfg". Ensure that required library paths are specified correctly, define the specified entity, or change the instantiation. If this entity represents Intel FPGA or third-party IP, generate the synthesis files for the IP.

**Comment by jotego** [comment]
The MiST version is broken too.

**Comment by birdybro** [comment]
Are you using Quartus 17.0.2 for the MiSTer version and Quartus 13.1 for the MiST version?

Those spaces should have no impact on compilation, it's commented out. I'll investigate...

**Comment by jotego** [comment]
Thank you, I tried Q20 indeed. Sorry for making the same mistake twice.

**Comment by birdybro** [comment]
It's no worries! You have a very complex tool chain with your other project. It's bound to happen.
