### ISSUE TITLE
the Clouds in wonderboy are wrong see image.

### ISSUE THREAD

**Issue by Retronerdy** [MiSTer-devel/SMS_MiSTer#14]
https://imgur.com/a/NybPasy

**Comment by damopinn** [comment]
I noticed a similar problem in Lucky dime caper. in the first level around some beaver hills and at the end of the level there is a cage and there is no transparency the bars cover the picture underneath.

**Comment by damopinn** [comment]
Hi, Clouds are fixed in Wonderboy now, and the problems in Lucky dime Caper.

**Comment by sorgelig** [comment]
good!
