### ISSUE TITLE
No smooth scrolling in game Master System Alex Kidd In Miracle World pal 50hz

### ISSUE THREAD

**Issue by Tempus002** [MiSTer-devel/SMS_MiSTer#141]
Not Smooth Scrolling and the music is too fast in 50 hz "Pal"

**Comment by birdybro** [comment]
Do you happen to have a recording from original hardware (a PAL SMS and not a PAL-modded SMS) for the video or sound to compare?

**Comment by Tempus002** [comment]
Thanks to your comments, I found where the problem came from.
I play on a CRT 31hz IIAMA, so that everything is perfect in PAL 50hz "scrolling and sound" you have to be with
vga_scaler=0.

I tested on CRT 15hz, scrolling and sound are perfect, I have no difference with my Master System PAL console.
Thanks for your help.

**Comment by birdybro** [comment]
No problem, glad you figured it out. Can you close the issue for us? Thanks!
