### ISSUE TITLE
Cannot disable lightgun crosshair

### ISSUE THREAD

**Issue by sbugliarisi** [MiSTer-devel/SMS_MiSTer#151]
When the lightgun is enabled in the SMS core there's an option to turn on or off the crosshair but it always stays on

**Comment by birdybro** [comment]
https://github.com/MiSTer-devel/SMS_MiSTer/compare/master...birdybro:lightgun-fix

This should fix it. Please test for me. It looks like 2 of the conditions were not setup correctly from the beginning, you probably didn't get 3 different sizes of lightgun crosshair either ;)

[SMS.zip](https://github.com/MiSTer-devel/SMS_MiSTer/files/9700879/SMS.zip)

**Comment by sbugliarisi** [comment]
Hmm that didn't work. I copied the rbf to my MiSTer and named it
"SMS-NEW", but when I run it there's no difference with the crosshair.
It'll switch sizes but it won't turn off. Am I supposed to
delete/rename my old SMS rbf?

**Comment by birdybro** [comment]
Nope, you tested it right. It was kind of a guess on my part, I'll check with Shane as he did this change originally.

**Comment by birdybro** [comment]
Figured it out, didn't realize that the nand for 2'b11 of that status bit was missing :)

**Comment by sbugliarisi** [comment]
Awesome! Thanks birdybro! So I guess this will eventually roll out through an update to MiSTer?

**Comment by birdybro** [comment]
Yup, you can get it with update_all with the unstable nightlies builds in a bit, or wait for the next release.

**Comment by sbugliarisi** [comment]
You’re a prince among men, thanks birdybro!

**Comment by birdybro** [comment]
This can be closed, as it's resolved now.
