### ISSUE TITLE
Core doesn't show any picture on my 4K TV half of the time

### ISSUE THREAD

**Issue by the-importer** [MiSTer-devel/SMS_MiSTer#18]
Hey there,

So I have my MiSTer hooked via HDMI on my Samsung 4K/UHD TV (UN55KU6290). Most of the time, this core will not show me any picture when loading any game, I'll only see the MiSTer interface when I hit the menu button. I'll hear a game play with the sound going through the HDMI, but no picture. It will however display via VGA on an old monitor that I've hooked via the IO board.

So ya, I get a blank image on my TV while the sound passes through but I do get the picture on my monitor. Sometime, after playing around with a bunch of different cores that work every time (SNES, Genesis, PC-Engine), it will eventually display on my TV , but that's on rare occasion.

I get a similar with the NES core and more often with the GameBoy core. Any idea of what's going on and how to fix it?

Thank you

**Comment by sorgelig** [comment]
Make sure you don't enable vsync_adjust option in ini. By default with no ini file MiSTer outputs standard 1280x720p60 video for every core. If this resolution doesn't work on your TV, then nothing i can do here. 
You may try to use 1920x1080p60 resolution actually.

**Comment by the-importer** [comment]
So with no INI file, the default is 0?

**Comment by sorgelig** [comment]
most parameters yes.

**Comment by M-Walrus** [comment]
No recent HDMI issues reported for SMS core. Recommending this 18-month old issue report to be closed.
