### ISSUE TITLE
Can't pause on MiST with 2-button DB9 controllers

### ISSUE THREAD

**Issue by RPGHiro** [MiSTer-devel/SMS_MiSTer#19]
I couldn't find any way to pause the game with 2-button DB9 pads, eg. with the SMS pad.
Older SMS cores for MiST had a pause option in the menu. Some games require it to be fully playable (like Alex Kidd in Miracle World). Other than that it works great, good work!

**Comment by gyurco** [comment]
AFAIK you cannot pause with the original two buttons pad, too. The pause button is on the SMS console itself. This is wired to the 3rd controller button. If you have a 2 buttons controller, then turn on joystick emulation via Num Lock, and use the left Alt (or Win) key for pause.

**Comment by RPGHiro** [comment]
Sorry for the late response. Thanks for pointing me to the joystick emulation on keyboard, that's really all I need. A menu option to pause/unpause may still help people who don't keep a kb connected but want to use a original SMS controller.

**Comment by iequalshane** [comment]
A pause button combo (Down + Button 1 + Button 2) has been added to SNAC support. Other DB9 solutions are not official, right?

**Comment by M-Walrus** [comment]
Issue report is for MiST, and does not seem relevant to the MiSTer core.  Recommending this issue report be closed.

**Comment by thehughhefner** [comment]
This issue can be closed since it is not related to MiSTer
