### ISSUE TITLE
Game Gear games that fail to get to gameplay

### ISSUE THREAD

**Issue by the1ross** [MiSTer-devel/SMS_MiSTer#29]
Today I went through the entire Game Gear library testing each and every game to see which didn't work. Out of the ones that didn't work, I tried about half in Kega Fusion and they all ran fine, so I don't believe any are bad rom dumps.

These games didn't boot at all and just display a black screen:
Gear Works
Kawasaki Super Bike Challenge
Lemmings
Micro Machines 
Micro Machines II
Pac Attack
Puyo Puyo 2/ Dr Robotnik's Mean Bean Machine
Puzlow Kids
SS Lucifer
Super Space Invaders
World Series baseball games / Major Pro Baseball

The next list of games do boot but the title screen graphics display incorrectly and part of the screen is cut off on some, they also crash before gameplay unless otherwise stated:
Chase HQ
Micky Mouse Castle of Illusion
Olympic Gold Barcelona
Prince of Persia
Predator 2
RC Grand Prix (this one has similar issues as the others in this list but it does manage to get to gameplay)
Super Kick Off
WWF Steel Cage

These games also refuse to get to gameplay:
Ceasor's Palace (game crashes after registering your name)
GP Rider (crashes at title screen when you push start)
Joe Montana Football (crashes at coin toss)
Mortal Kombat 2 (screen goes black after Acclaim licensing info)
NFL 95 (crashes at Sega logo)
Pop Breaker (at title screen you can move up and down between game options but it wont register a button press, so you can't start the game)
Primal Rage (crashes at the title screen after the intro)
Stargate (hangs at Acclaim logo)
Tanto R (screen goes black after title screen, game doesn't boot)

Other glitches/ bugs I noticed:
X-Men games (X-Men logo on title screen is glitched)

**Comment by the1ross** [comment]
Outrun and Outrun Europa also refuse to boot and just display a black screen.

**Comment by theflynn49** [comment]
this fixes most of the "don't boot" list : [https://github.com/theflynn49/SMS_MiSTer/commit/53f909fb1205fe4a542c535c3c292c2bb66e6b9f](https://github.com/theflynn49/SMS_MiSTer/commit/53f909fb1205fe4a542c535c3c292c2bb66e6b9f)

**Comment by theflynn49** [comment]
> These games didn't boot at all and just display a black screen:
> Gear Works    ... Done
> Kawasaki Super Bike Challenge  ... Done
> Lemmings  ... Done
> Micro Machines  ... Done
> Micro Machines II  ... Done
> Pac Attack  ... TODO freeze with black screen
> Puyo Puyo 2/ ... Done
> Dr Robotnik's Mean Bean Machine ... (game not found) 
> Puzlow Kids  ... Done 
> SS Lucifer ... (game not found)
> Super Space Invaders   ... Done
> World Series baseball games ... TODO freeze with black screen 
> Major Pro Baseball ... TODO freeze with black screen
> 
> The next list of games do boot but the title screen graphics display incorrectly and part of the screen is cut off on some, they also crash before gameplay unless otherwise stated:
> Chase HQ  TODO GG-SMS type of game
> Micky Mouse Castle of Illusion ... TODO freeze with black screen
> Olympic Gold Barcelona  ... TODO GG-SMS type of game
> Prince of Persia  ... TODO freeze with black screen
> Predator 2 (game not found)
> RC Grand Prix (this one has similar issues as the others in this list but it does manage to get to gameplay)  ... TODO GG-SMS type of game
> Super Kick Off ... TODO freeze with black screen
> WWF Steel Cage ... TODO freeze with black screen
notice : all these games belong to the SMS-GG tagged category : http://www.smspower.org/Tags/SMS-GG

> 
> These games also refuse to get to gameplay:
> Ceasor's Palace (game crashes after registering your name) ... (game not found)
> GP Rider (crashes at title screen when you push start)  ... Done (Works)
> Joe Montana Football (crashes at coin toss)  ... KO do not start at all
> Mortal Kombat 2 (screen goes black after Acclaim licensing info)  ... TODO
> NFL 95 (crashes at Sega logo)  ... Done (Works)
> Pop Breaker (at title screen you can move up and down between game options but it wont register a button press, so you can't start the game) ... TODO
> Primal Rage (crashes at the title screen after the intro) ... TODO : Crashes even before with me
> Stargate (hangs at Acclaim logo) ... TODO
> Tanto R (screen goes black after title screen, game doesn't boot) ... Done (Works)
> 
> X-Men games (X-Men logo on title screen is glitched)  ...  TODO
> Outrun refuse to boot and just display a black screen. ... Done (Works) 
> Outrun Europa also refuse to boot and just display a black screen.  ... TODO (freeze with garbled screen)

**Comment by the1ross** [comment]
Thanks! Awesome work mate. I'll check some of these out when I get home. Out of the games left to do, most can be played on Master System (or other systems) anyway. Being an exclusive shmup to the system, Pop Breaker is probably the only really desirable game left on the core to get working.

**Comment by the1ross** [comment]
Predator 2 does certainly exist by the way, it got a US and European release.  https://segaretro.org/Predator_2

**Comment by theflynn49** [comment]
Hello. Thanks for your dedication trying all these games ;) I finally found Predator2.
Be careful to use the lastest core sources to date if you want to try these games, as the binaries have not been published yet.

**Comment by gyurco** [comment]
SMS-GG type games: just rename them to .sms or .bin

**Comment by theflynn49** [comment]
... hmmmpff I was getting ready to add an option in the config menu for that; 
Emulitious kind of detects this automatically, it is using the region code at $7FFF but it's unclear.
the trick works for Chase HQ I just tried it ... master elegant move Mister Gyurco :)

**Comment by gyurco** [comment]
The original GG has a pin on the cartridge port which switches to SMS mode. That can be emulated by OSD or renaming the file :)

**Comment by theflynn49** [comment]
If you ask me, it's worth a line of explanation in the  README.md file...

**Comment by theflynn49** [comment]
Ok, I have updated my comment above with all the status of all games.
The status **NOT SURE** is a weird bug someone might look at in the future since other good emulators don't support them either.
There are two interesting bugs I will look into asap : the lack of the GG parallel and serial ports, and the sprite double-sized bug.
Most of the rest works with the latest core.

**Comment by theflynn49** [comment]
#35 should fix X-Men and Pac Attack

**Comment by theflynn49** [comment]
#36 Should fix the GG-specific hardware issues

Now I need to rest a little ;) :sleeping_bed:

**Comment by sorgelig** [comment]
Everybody needs a rest :)

**Comment by theflynn49** [comment]
"Primal Rage" in fact has a bug : it uses the normal mapper, but writes something at address 0000 unlashing hell.
So I had to write a stronger mapper selection mechanism. -> next release

**Comment by theflynn49** [comment]
I fixed Pop Breaker, it needed a "Japan" region parameter.

The only two games I couldn't fix are 
-World Series baseball games
-Major Pro Baseball 

It seems to me that they use a standard mapper, and then they mess with address $8000; so they probably have a dedicated hardware or mapper. I couldn't find any more info about this, so I give it up.

I will make a PR within minutes, if someone wants to make some early testing, he can use my [latest core](https://github.com/theflynn49/MiSTer_cores)

**Comment by sorgelig** [comment]
Probably they use EEPROM as many sport games on Genesis.
From my point of view these games are plain rubbish - not worth the effort.

**Comment by theflynn49** [comment]
lol ... I was just trying to make a full strike with this issue :D

**Comment by the1ross** [comment]
That's excellent. Can't wait to get home and try Pop Breaker on the big screen. 

It'll be a struggle, but I think I can just about live without Major Pro Baseball in my life.

**Comment by the1ross** [comment]
Ok, tried a few of the games that didn't work beforr and they're fine now. Pop Breaker still has the same issue, but I guess I misunderstood you and that'll be fixed in the next release.

**Comment by theflynn49** [comment]
Did you use my [latest core](https://github.com/theflynn49/MiSTer_cores) ?

**Comment by theflynn49** [comment]
Micromachines II is back online ;)

**Comment by thehughhefner** [comment]
Has this issue been solved? If so then this ticket can be closed
