### ISSUE TITLE
Top row of pixels scrolls horizontally with the background, but it shouldn't

### ISSUE THREAD

**Issue by c0d3h4x0r** [MiSTer-devel/SMS_MiSTer#37]
All SMS games with horizontal scrolling and a fixed status area along the top (such as Transbot or Wonder Boy III) exhibit a visual glitch: the top row of pixels (in the status bar area near the top) scrolls along with the background, rather than staying fixed in place.  You can see this in the attached screenshot (taken from the 20190411 core release for MiSTer).

[Wonder Boy III Glitch](https://user-images.githubusercontent.com/24398884/56466046-f3b2de80-63bf-11e9-821d-c6bb21a48329.jpg)

**Comment by theflynn49** [comment]
It's probably fixed in the latest core, but it's not released yet.
Either compile the core with the latest sources or use mine : [https://github.com/theflynn49/MiSTer_cores](https://github.com/theflynn49/MiSTer_cores)

**Comment by sorgelig** [comment]
it's released already

**Comment by c0d3h4x0r** [comment]
Yep, that fixes it!  Thanks!
