### ISSUE TITLE
Aladdin GameGear button issue

### ISSUE THREAD

**Issue by flywithsean** [MiSTer-devel/SMS_MiSTer#61]
When playing the game with the USA ROM for GameGear after the first jump from one building to the next in the second section of the game the jump button no longer registers. Duplicated across multiple GameGear ROMs but the SMS ROM is fine.

**Comment by iequalshane** [comment]
I have a fix for this in hand, but I want to test the other problematic games. Which ones also had issues?

**Comment by flywithsean** [comment]
That is the only game I have played that has had that issue

**Comment by iequalshane** [comment]
Thank you for the info. This should now be resolved in the current code, which will be available on the next release.

**Comment by thehughhefner** [comment]
Has this issue been solved? If so then this ticket can be closed
