### ISSUE TITLE
FM Sound option gone

### ISSUE THREAD

**Issue by ThreepwoodLeBrush** [MiSTer-devel/SMS_MiSTer#71]
Since the latest framework update the FM Sound Option is gone.

**Comment by iequalshane** [comment]
This was only supposed to be hidden when a Game Gear game is loaded, which disables the feature. I know the OSD options got an update since I made this change, so I'll check to see if this got messed up somehow.

**Comment by iequalshane** [comment]
This line:
"P1H2OC,SMS FM sound,Enable,Disable;",
Should be:
"H2P1OC,SMS FM sound,Enable,Disable;",
I can fix it later tonight.
