### ISSUE TITLE
Master System Walter Payton Football doesn't start 

### ISSUE THREAD

**Issue by KidpandaAG** [MiSTer-devel/SMS_MiSTer#73]
Walter Payton Football doesn't boot, gets stuck on a red screen after boot.

**Comment by bibou42** [comment]
It works for me.

**Comment by meauxdal** [comment]
This game still shows a flashing red screen after the Sega logo in the latest SMS build.

Rom used: https://datomatic.no-intro.org/index.php?page=show_record&s=26&n=0414 
CRC32 3D55759B

**Comment by bibou42** [comment]
I'm using the same rom and it's working.

![Capture](https://user-images.githubusercontent.com/18500303/109228527-3e72be00-77c2-11eb-90ec-5cfe3a14145d.JPG)
![20210225_232615-Walter Payton Football (USA)](https://user-images.githubusercontent.com/18500303/109228552-47638f80-77c2-11eb-9d7a-e0ccce37e8e8.png)
![20210225_232736-Walter Payton Football (USA)](https://user-images.githubusercontent.com/18500303/109228556-492d5300-77c2-11eb-98f0-3a18dcf7b74a.png)

**Comment by meauxdal** [comment]
That's interesting. Here's what I see:

https://youtu.be/4tTtqzwqyv8

![image](https://user-images.githubusercontent.com/68095521/109253278-70cdec80-77bd-11eb-83a7-18702f8474ca.png)

**Comment by bibou42** [comment]
Here are my settings if it can help :

![image](https://user-images.githubusercontent.com/18500303/109388039-fdcf8d80-7904-11eb-8cbb-94f26ceeedac.png)
![image](https://user-images.githubusercontent.com/18500303/109388057-12ac2100-7905-11eb-8f2c-e99e5591a6d3.png)

**Comment by meauxdal** [comment]
Thank you for those images, this allowed me to boot the game. Our only difference in settings was the SMS FM sound toggle - mine was Enabled and yours Disabled. Disabling the toggle allowed me to bypass the red screen immediately. This issue can likely be closed.

https://www.youtube.com/watch?v=vFewhDG8DY8

**Comment by bibou42** [comment]
I confirm that with FM Sound Enabled, I have the same issue.

**Comment by bibou42** [comment]
@KidpandaAG You can close this issue. To play this game, FM Sound should be disabled.
I tried in Mednafen, this game behaves the same way than MiSTer with FM Sound enabled.
