### ISSUE TITLE
Game Gear: Madou Monogatari II and III do not play voice samples correctly

### ISSUE THREAD

**Issue by TheOpponent** [MiSTer-devel/SMS_MiSTer#74]
In these games, voices play at a nearly inaudible level. Voice samples in the other two games in the series, Madou Monogatari I and A, do have voice samples at the correct volume.

**Comment by birdybro** [comment]
Just tested and https://github.com/MiSTer-devel/SMS_MiSTer/pull/138 does not resolve this either.

**Comment by wwark** [comment]
It seems resolved on my side with the commit #138

**Comment by birdybro** [comment]
In Madou Monogatari II just after the Sega logo the sound the character makes when opening it's mouth is distorted and quiet in the latest build, sounds like static. This was the same behavior as the previous build.

https://youtu.be/p_LgWXtyukY?t=16 - a software emulator example, but a decent example nonetheless.

**Comment by wwark** [comment]
It is not my case.
On the last release of SMS the sound of open mouth in Madou Monogatari II  is off (no sound at all). 
With the last commit, I have the sound of open mouth but maybe it requires more work to match the one on emulator/real hardware.

**Comment by Thelypody** [comment]
It also looks like fixed on my end. On 20220620 release of the core Carbuncle (orange guy) is silent in Madou Monogatari II intro. With an unofficial build with #138 applied, he shouts with a very clear vocal sample. No sounds of static present.

**Comment by birdybro** [comment]
Okay all of a sudden it's working for me?! Not sure what's different when I go upstairs to my development MiSTer... hrmm. Well it looks like this is resolved!! :)

**Comment by wwark** [comment]
Great !
Do you think it could fix some sound issues on Genesis Core ?

**Comment by birdybro** [comment]
Maybe, but I kinda doubt it. The only currently open PSG issue where it is completely missing is due to the bus arbiter issues most likely. I could try it though and see if demons of asteborg gets resolved too.

**Comment by birdybro** [comment]
This issue can be closed.
