### ISSUE TITLE
Aspect ratio is incorrect when border is disabled

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/SMS_MiSTer#75]
While playing Master of Darkness on the SMS core today, I realized that the only way to get an accurate aspect ratio (accurate to what is displayed on CRT), is to keep the border turned on. This makes the viewable area *much* smaller when integer scaling, but it is currently the only way to have an accurate aspect ratio for this core.

Example in Master of Darkness:  Slightly rectangular boxes in the UI at the top are perfectly square when border is disabled. After enabling the border, you can clearly see they are a bit rectangular, as they appear on CRT.

**Comment by M-Walrus** [comment]
adding example screenshots from the game Ghostbusters on SMS:

border off:
![SMS core border off](https://user-images.githubusercontent.com/40709481/96103435-5134c800-0e9d-11eb-8ee7-ddb8d1fb53bb.PNG)

border on:
![SMS core border on](https://user-images.githubusercontent.com/40709481/96103463-598d0300-0e9d-11eb-851a-d95bd227a8d8.PNG)

**Comment by Kitrinx** [comment]
for any changes in visible size you need to have conditional for aspect for different visible area. See genesis or NES core for an example.

**Comment by sorgelig** [comment]
i've pushed changes to aspect ratio

**Comment by M-Walrus** [comment]
confirmed fixed in recent update.
