### ISSUE TITLE
5x Vertical Crop

### ISSUE THREAD

**Issue by MJY71** [MiSTer-devel/SMS_MiSTer#81]
`Vertical Crop: 216p (5x)` seems to have no noticeable effect. Would the setting even work with this particular core when the system's native resolution is 256x192?

**Comment by M-Walrus** [comment]
The 5x feature only works in the SMS core when the border is on.  You'll want to keep this on anyways, if aspect ratio is important to you, since the non-bordered option currently has the incorrect AR

**Comment by sorgelig** [comment]
i will make 216p hardcoded for SMS and Colecovision when border is enabled. Option will be removed.

**Comment by MJY71** [comment]
Understood. Thank you both for the explanations.
