### ISSUE TITLE
Crop option doesn't do anything on the SMS/GG core

### ISSUE THREAD

**Issue by Alex-Catalin** [MiSTer-devel/SMS_MiSTer#82]
I have vscale_mode, vscale_border, scandoubler set to 0, I have scanlines enabled and when I toggle the crop option in the menu of the core, nothing happens, it's completely ignored.

On all the other cores where the crop option has been added, when I toggle it, the screen flashes and I get the 5X height on the image.

**Comment by sorgelig** [comment]
https://github.com/MiSTer-devel/SMS_MiSTer/issues/81

**Comment by birdybro** [comment]
This issue can be closed.
