### ISSUE TITLE
No difference between Narrower and Wider HV-Integer 

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/SMS_MiSTer#86]
I use 1920x1440 (there's no difference between Narrower and Wider HV-Integer in this mode - not sure why.

**Comment by sorgelig** [comment]
"Narrower" is rounded down integer while "wider" is rounded up integer.
if wider option gives resolution higher than screen, then it falls back to narrower.
This is correct behavior.

**Comment by dfilskov** [comment]
Ah - thank you. I thought it was meant to always provide a wider and narrower image than the original if possible (by squeezing or expanding the width while keeping the height - or - by squeezing or expanding the height while keeping the width).

**Comment by sorgelig** [comment]
There is no point to squeeze further if current size is already rounded down, so it's already narrower than original aspect ratio.

**Comment by dfilskov** [comment]
Ah - yes, that makes sense, then. So if it's already too narrow the integer image could only be better if squeezed in the height?
